// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

import type { Metadata } from 'next';
import dynamicNext from 'next/dynamic';
import RightSide from '@/components/rightSide';
import LeftSide from '@/components/leftSide';
import AntdStyleRegistry from '@/lib/antd-registry';
import data from '@blog/communication';
import './index.scss';
// 这里防止在代码中引用 SSG 不支持的一些功能
export const dynamic = 'error';

export const metadata: Metadata = {
  title: {
    template: `%s | ${data.user.name} 的个人博客`,
    default: `${data.user.name} 的个人博客`,
  },
  description: '记录生活随笔以及技术博客',
};
const Statistics = dynamicNext(() => import('./statistics'), { ssr: false });
const AssetsWatch = dynamicNext(() => import('./assetsWatch'), { ssr: false });

export default function RootLayout({ children, ...otherProps }: { children: React.ReactNode; otherProps: any }) {
  return (
    <html lang="zh">
      <head></head>
      <body>
        <AntdStyleRegistry>
          <LeftSide></LeftSide>
          <div className="content">{children}</div>
          <RightSide></RightSide>
        </AntdStyleRegistry>
        <Statistics></Statistics>
        <AssetsWatch></AssetsWatch>
      </body>
    </html>
  );
}
